services:
  - type: web
    name: email-service
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm use 18.17.0
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install --production
      echo "✅ Build complete"
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /
